# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 710)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("./Compile/mainwindowIcon.PNG")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.Tab_Exclude = QtWidgets.QTabWidget(self.centralwidget)
        self.Tab_Exclude.setGeometry(QtCore.QRect(0, 0, 911, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab_Exclude.sizePolicy().hasHeightForWidth())
        self.Tab_Exclude.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Tab_Exclude.setFont(font)
        self.Tab_Exclude.setAcceptDrops(False)
        self.Tab_Exclude.setAutoFillBackground(True)
        self.Tab_Exclude.setElideMode(QtCore.Qt.ElideNone)
        self.Tab_Exclude.setDocumentMode(False)
        self.Tab_Exclude.setObjectName("Tab_Exclude")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.Result = QtWidgets.QTextEdit(self.tab)
        self.Result.setGeometry(QtCore.QRect(199, 360, 671, 241))
        self.Result.setStyleSheet("font: 10pt \"Arial\";")
        self.Result.setObjectName("Result")
        self.projectDir = QtWidgets.QLabel(self.tab)
        self.projectDir.setGeometry(QtCore.QRect(21, 11, 95, 27))
        self.projectDir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.projectDir.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.projectDir.setObjectName("projectDir")
        self.ProjectName_2 = QtWidgets.QLineEdit(self.tab)
        self.ProjectName_2.setEnabled(False)
        self.ProjectName_2.setGeometry(QtCore.QRect(199, 11, 671, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProjectName_2.sizePolicy().hasHeightForWidth())
        self.ProjectName_2.setSizePolicy(sizePolicy)
        self.ProjectName_2.setStyleSheet("font: 14pt \"Arial\";")
        self.ProjectName_2.setText("")
        self.ProjectName_2.setObjectName("ProjectName_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(21, 360, 95, 27))
        self.label_5.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(21, 340, 849, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(21, 45, 95, 27))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(21, 250, 95, 27))
        self.label_4.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.LINKFLAGName = QtWidgets.QTextEdit(self.tab)
        self.LINKFLAGName.setGeometry(QtCore.QRect(199, 220, 671, 111))
        self.LINKFLAGName.setStyleSheet("font: 12pt \"Arial\";")
        self.LINKFLAGName.setObjectName("LINKFLAGName")
        self.ProjectName = QtWidgets.QLineEdit(self.tab)
        self.ProjectName.setEnabled(True)
        self.ProjectName.setGeometry(QtCore.QRect(199, 45, 671, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProjectName.sizePolicy().hasHeightForWidth())
        self.ProjectName.setSizePolicy(sizePolicy)
        self.ProjectName.setStyleSheet("font: 14pt \"Arial\";")
        self.ProjectName.setText("")
        self.ProjectName.setObjectName("ProjectName")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(21, 79, 172, 27))
        self.label_2.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.HithTecDir = QtWidgets.QLineEdit(self.tab)
        self.HithTecDir.setGeometry(QtCore.QRect(199, 79, 671, 28))
        self.HithTecDir.setStyleSheet("font: 14pt \"Arial\";")
        self.HithTecDir.setObjectName("HithTecDir")
        self.GCCFLAGName = QtWidgets.QTextEdit(self.tab)
        self.GCCFLAGName.setGeometry(QtCore.QRect(199, 113, 671, 101))
        self.GCCFLAGName.setStyleSheet("font: 12pt \"Arial\";")
        self.GCCFLAGName.setObjectName("GCCFLAGName")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(21, 150, 95, 27))
        self.label_3.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.Tab_Exclude.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.includeList = QtWidgets.QListWidget(self.tab_2)
        self.includeList.setGeometry(QtCore.QRect(0, 0, 901, 481))
        self.includeList.setObjectName("includeList")
        self.framePower = QtWidgets.QFrame(self.tab_2)
        self.framePower.setGeometry(QtCore.QRect(60, 0, 801, 81))
        self.framePower.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePower.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePower.setObjectName("framePower")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 490, 541, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addPath1 = QtWidgets.QPushButton(self.layoutWidget)
        self.addPath1.setObjectName("addPath1")
        self.horizontalLayout.addWidget(self.addPath1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.delPath1 = QtWidgets.QPushButton(self.layoutWidget)
        self.delPath1.setObjectName("delPath1")
        self.horizontalLayout.addWidget(self.delPath1)
        self.layoutWidget.raise_()
        self.framePower.raise_()
        self.includeList.raise_()
        self.Tab_Exclude.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.excludeList = QtWidgets.QListWidget(self.tab_3)
        self.excludeList.setGeometry(QtCore.QRect(0, 0, 901, 481))
        self.excludeList.setObjectName("excludeList")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 490, 541, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addPath2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.addPath2.setObjectName("addPath2")
        self.horizontalLayout_4.addWidget(self.addPath2)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.delPath2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.delPath2.setObjectName("delPath2")
        self.horizontalLayout_4.addWidget(self.delPath2)
        self.Tab_Exclude.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")


        MainWindow.setStatusBar(self.statusBar)


        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 23))
        self.menubar.setObjectName("menubar")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menusave")
        self.menusave = QtWidgets.QMenu(self.menubar)
        self.menusave.setObjectName("menusave")
        self.menubuild = QtWidgets.QMenu(self.menubar)
        self.menubuild.setObjectName("menubuild")
        self.quitApp = QtWidgets.QMenu(self.menubar)
        self.quitApp.setObjectName("quitApp")
        MainWindow.setMenuBar(self.menubar)
        self.actionopen_project = QtWidgets.QAction(MainWindow)
        self.actionopen_project.setObjectName("actionsave_project")
        self.actionsave_project = QtWidgets.QAction(MainWindow)
        self.actionsave_project.setObjectName("actionsave_project")
        self.actionbuild = QtWidgets.QAction(MainWindow)
        self.actionbuild.setObjectName("actionbuild")
        self.actionclean = QtWidgets.QAction(MainWindow)
        self.actionclean.setObjectName("actionclean")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuopen.addAction(self.actionopen_project)
        self.menusave.addAction(self.actionsave_project)
        self.menubuild.addAction(self.actionbuild)
        self.menubuild.addAction(self.actionclean)
        self.quitApp.addAction(self.actionexit)
        self.menubar.addAction(self.menuopen.menuAction())
        self.menubar.addAction(self.menusave.menuAction())
        self.menubar.addAction(self.menubuild.menuAction())
        self.menubar.addAction(self.quitApp.menuAction())

        self.retranslateUi(MainWindow)
        self.Tab_Exclude.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XMiCom"))
        self.projectDir.setText(_translate("MainWindow", "工程路径："))
        self.label_5.setText(_translate("MainWindow", "输出结果："))
        self.label.setText(_translate("MainWindow", "工程名字："))
        self.label_4.setText(_translate("MainWindow", "链接指令："))
        self.label_2.setText(_translate("MainWindow", "Hithtec安装路径："))
        self.label_3.setText(_translate("MainWindow", "编译指令："))
        self.Tab_Exclude.setTabText(self.Tab_Exclude.indexOf(self.tab), _translate("MainWindow", "配置"))
        self.includeList.setToolTip(_translate("MainWindow", "<html><head/><body><p>1</p></body></html>"))
        self.addPath1.setText(_translate("MainWindow", "添加路径"))
        self.delPath1.setText(_translate("MainWindow", "删除全部路径"))
        self.Tab_Exclude.setTabText(self.Tab_Exclude.indexOf(self.tab_2), _translate("MainWindow", "IncludePath"))
        self.excludeList.setToolTip(_translate("MainWindow", "<html><head/><body><p>1</p></body></html>"))
        self.addPath2.setText(_translate("MainWindow", "添加路径"))
        self.delPath2.setText(_translate("MainWindow", "删除全部路径"))
        self.Tab_Exclude.setTabText(self.Tab_Exclude.indexOf(self.tab_3), _translate("MainWindow", "ExcludePath"))
        self.menuopen.setTitle(_translate("MainWindow", "打开"))
        self.menusave.setTitle(_translate("MainWindow", "保存"))
        self.menubuild.setTitle(_translate("MainWindow", "构建"))
        self.quitApp.setTitle(_translate("MainWindow", "退出"))
        self.actionopen_project.setText(_translate("MainWindow", "打开工程"))
        self.actionsave_project.setText(_translate("MainWindow", "保存工程"))
        self.actionopen_project.setToolTip(_translate("MainWindow", "打开工程"))
        self.actionbuild.setText(_translate("MainWindow", "build"))
        self.actionclean.setText(_translate("MainWindow", "clean"))
        self.actionexit.setText(_translate("MainWindow", "exit"))

