# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 794)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("./Compile/mainwindowIcon.PNG")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("frame{border:1px solid rgb(0,255,0)}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 10, 841, 451))
        self.stackedWidget.setToolTip("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidget.setObjectName("stackedWidget")
        self.proConfig = QtWidgets.QWidget()
        self.proConfig.setObjectName("proConfig")
        self.ProjectName_2 = QtWidgets.QLineEdit(self.proConfig)
        self.ProjectName_2.setEnabled(False)
        self.ProjectName_2.setGeometry(QtCore.QRect(130, 30, 671, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProjectName_2.sizePolicy().hasHeightForWidth())
        self.ProjectName_2.setSizePolicy(sizePolicy)
        self.ProjectName_2.setStyleSheet("font: 14pt \"Arial\";")
        self.ProjectName_2.setText("")
        self.ProjectName_2.setObjectName("ProjectName_2")
        self.label_2 = QtWidgets.QLabel(self.proConfig)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 121, 111))
        self.label_2.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.proConfig)
        self.label.setGeometry(QtCore.QRect(10, 90, 121, 27))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.projectDir = QtWidgets.QLabel(self.proConfig)
        self.projectDir.setGeometry(QtCore.QRect(10, 11, 121, 27))
        self.projectDir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.projectDir.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.projectDir.setObjectName("projectDir")
        self.ProjectName = QtWidgets.QLineEdit(self.proConfig)
        self.ProjectName.setEnabled(True)
        self.ProjectName.setGeometry(QtCore.QRect(130, 120, 671, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ProjectName.sizePolicy().hasHeightForWidth())
        self.ProjectName.setSizePolicy(sizePolicy)
        self.ProjectName.setStyleSheet("font: 14pt \"Arial\";")
        self.ProjectName.setText("")
        self.ProjectName.setObjectName("ProjectName")
        self.HithTecDir = QtWidgets.QLineEdit(self.proConfig)
        self.HithTecDir.setGeometry(QtCore.QRect(130, 230, 671, 31))
        self.HithTecDir.setStyleSheet("font: 14pt \"Arial\";")
        self.HithTecDir.setObjectName("HithTecDir")
        self.label_3 = QtWidgets.QLabel(self.proConfig)
        self.label_3.setGeometry(QtCore.QRect(140, 210, 531, 16))
        self.label_3.setStyleSheet("font: 10pt \"Arial\";color:rgb(85, 85, 85)")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.proConfig)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 95, 27))
        self.label_5.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label_5.setObjectName("label_5")
        self.GCCFLAGName = QtWidgets.QTextEdit(self.page)
        self.GCCFLAGName.setGeometry(QtCore.QRect(110, 60, 671, 161))
        self.GCCFLAGName.setStyleSheet("font: 12pt \"Arial\";")
        self.GCCFLAGName.setObjectName("GCCFLAGName")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.LINKFLAGName = QtWidgets.QTextEdit(self.page_2)
        self.LINKFLAGName.setGeometry(QtCore.QRect(100, 40, 721, 111))
        self.LINKFLAGName.setStyleSheet("font: 12pt \"Arial\";")
        self.LINKFLAGName.setObjectName("LINKFLAGName")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 95, 27))
        self.label_4.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label_4.setObjectName("label_4")
        self.frame11 = QtWidgets.QFrame(self.page_2)
        self.frame11.setGeometry(QtCore.QRect(100, 160, 351, 271))
        self.frame11.setStyleSheet("QFrame{border:1px solid rgb(131, 131, 131) ;background:rgb(255, 255, 255) }\n"
"QListView{background:#ffffff}\n"
"QLabel{border:none}\n"
"")
        self.frame11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame11.setObjectName("frame11")
        self.Llist = QtWidgets.QListView(self.frame11)
        self.Llist.setEnabled(True)
        self.Llist.setGeometry(QtCore.QRect(0, 40, 351, 231))
        self.Llist.setObjectName("Llist")
        self.label_6 = QtWidgets.QLabel(self.frame11)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 261, 21))
        self.label_6.setObjectName("label_6")
        self.add1 = QtWidgets.QToolButton(self.frame11)
        self.add1.setGeometry(QtCore.QRect(280, 9, 31, 31))
        self.add1.setStyleSheet("QToolButton{border-image: url(:/newPrefix/add.PNG)}\n"
"")
        self.add1.setText("")
        self.add1.setIconSize(QtCore.QSize(40, 40))
        self.add1.setObjectName("add1")
        self.del1 = QtWidgets.QToolButton(self.frame11)
        self.del1.setGeometry(QtCore.QRect(310, 7, 31, 33))
        self.del1.setStyleSheet("QToolButton{border-image: url(:/newPrefix/del.PNG)}\n"
"")
        self.del1.setText("")
        self.del1.setIconSize(QtCore.QSize(40, 40))
        self.del1.setObjectName("del1")
        self.add1.raise_()
        self.Llist.raise_()
        self.label_6.raise_()
        self.del1.raise_()
        self.frame11_2 = QtWidgets.QFrame(self.page_2)
        self.frame11_2.setGeometry(QtCore.QRect(470, 160, 351, 271))
        self.frame11_2.setStyleSheet("QFrame{border:1px solid rgb(131, 131, 131) ;background:rgb(255, 255, 255) }\n"
"QListView{background:#ffffff}\n"
"QLabel{border:none}\n"
"")
        self.frame11_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame11_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame11_2.setObjectName("frame11_2")
        self.llist = QtWidgets.QListView(self.frame11_2)
        self.llist.setEnabled(True)
        self.llist.setGeometry(QtCore.QRect(0, 40, 351, 231))
        self.llist.setObjectName("llist")
        self.label_7 = QtWidgets.QLabel(self.frame11_2)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 261, 21))
        self.label_7.setObjectName("label_7")
        self.add2 = QtWidgets.QToolButton(self.frame11_2)
        self.add2.setGeometry(QtCore.QRect(280, 9, 31, 31))
        self.add2.setStyleSheet("QToolButton{border-image: url(:/newPrefix/add.PNG)}")
        self.add2.setText("")
        self.add2.setIconSize(QtCore.QSize(40, 40))
        self.add2.setObjectName("add2")
        self.del2 = QtWidgets.QToolButton(self.frame11_2)
        self.del2.setGeometry(QtCore.QRect(310, 7, 31, 33))
        self.del2.setStyleSheet("QToolButton{border-image: url(:/newPrefix/del.PNG)}")
        self.del2.setText("")
        self.del2.setIconSize(QtCore.QSize(40, 40))
        self.del2.setObjectName("del2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.layoutWidget = QtWidgets.QWidget(self.page_3)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 389, 541, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addPath1 = QtWidgets.QPushButton(self.layoutWidget)
        self.addPath1.setObjectName("addPath1")
        self.horizontalLayout.addWidget(self.addPath1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.delPath1 = QtWidgets.QPushButton(self.layoutWidget)
        self.delPath1.setObjectName("delPath1")
        self.horizontalLayout.addWidget(self.delPath1)
        self.includeList = QtWidgets.QListWidget(self.page_3)
        self.includeList.setGeometry(QtCore.QRect(3, 3, 831, 371))
        self.includeList.setObjectName("includeList")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.excludeList = QtWidgets.QListWidget(self.page_4)
        self.excludeList.setGeometry(QtCore.QRect(3, 3, 831, 371))
        self.excludeList.setObjectName("excludeList")
        self.layoutWidget_3 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(3, 389, 541, 75))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addPath2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.addPath2.setObjectName("addPath2")
        self.horizontalLayout_4.addWidget(self.addPath2)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.delPath2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.delPath2.setObjectName("delPath2")
        self.horizontalLayout_4.addWidget(self.delPath2)
        self.stackedWidget.addWidget(self.page_4)
        self.Result = QtWidgets.QTextEdit(self.centralwidget)
        self.Result.setEnabled(True)
        self.Result.setGeometry(QtCore.QRect(130, 510, 841, 231))
        self.Result.setStyleSheet("font: 10pt \"Arial\";")
        self.Result.setObjectName("Result")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 500, 95, 27))
        self.label_8.setStyleSheet("font: 12pt \"Agency FB\";\n"
"font: 87 14pt \"Arial Black\";")
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 483, 991, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(5, 10, 121, 451))
        self.listWidget.setStyleSheet("QListView::item{height:50px}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 23))
        self.menubar.setObjectName("menubar")
        self.menubuild = QtWidgets.QMenu(self.menubar)
        self.menubuild.setObjectName("menubuild")
        self.quitApp = QtWidgets.QMenu(self.menubar)
        self.quitApp.setObjectName("quitApp")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menuopen")
        self.menusave = QtWidgets.QMenu(self.menubar)
        self.menusave.setObjectName("menusave")
        MainWindow.setMenuBar(self.menubar)
        self.actionopen_project = QtWidgets.QAction(MainWindow)
        self.actionopen_project.setObjectName("actionopen_project")
        self.actionbuild = QtWidgets.QAction(MainWindow)
        self.actionbuild.setObjectName("actionbuild")
        self.actionclean = QtWidgets.QAction(MainWindow)
        self.actionclean.setObjectName("actionclean")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionsave_project = QtWidgets.QAction(MainWindow)
        self.actionsave_project.setObjectName("actionsave_project")
        self.menubuild.addAction(self.actionbuild)
        self.menubuild.addAction(self.actionclean)
        self.quitApp.addAction(self.actionexit)
        self.menuopen.addAction(self.actionopen_project)
        self.menusave.addAction(self.actionsave_project)
        self.menubar.addAction(self.menuopen.menuAction())
        self.menubar.addAction(self.menusave.menuAction())
        self.menubar.addAction(self.menubuild.menuAction())
        self.menubar.addAction(self.quitApp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XMiCom"))
        self.label_2.setText(_translate("MainWindow", "Hithtec安装路径："))
        self.label.setText(_translate("MainWindow", "工程名字："))
        self.projectDir.setText(_translate("MainWindow", "工程路径："))
        self.label_3.setText(_translate("MainWindow", "例如：D:\\HighTec\\toolchains\\tricore\\v4.6.6.1"))
        self.label_5.setText(_translate("MainWindow", "编译指令："))
        self.label_4.setText(_translate("MainWindow", "链接指令："))
        self.label_6.setText(_translate("MainWindow", "Library Path(-L)"))
        self.label_7.setText(_translate("MainWindow", "Libraries(-l)"))
        self.addPath1.setText(_translate("MainWindow", "添加路径"))
        self.delPath1.setText(_translate("MainWindow", "删除全部路径"))
        self.includeList.setToolTip(_translate("MainWindow", "<html><head/><body><p>1</p></body></html>"))
        self.excludeList.setToolTip(_translate("MainWindow", "<html><head/><body><p>1</p></body></html>"))
        self.addPath2.setText(_translate("MainWindow", "添加路径"))
        self.delPath2.setText(_translate("MainWindow", "删除全部路径"))
        self.label_8.setText(_translate("MainWindow", "输出结果："))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "工程配置"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "编译配置"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "链接配置"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "IncludePath"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "ExcludePath"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.menubuild.setTitle(_translate("MainWindow", "构建"))
        self.quitApp.setTitle(_translate("MainWindow", "退出"))
        self.menuopen.setTitle(_translate("MainWindow", "打开"))
        self.menusave.setTitle(_translate("MainWindow", "保存"))
        self.actionopen_project.setText(_translate("MainWindow", "打开工程"))
        self.actionopen_project.setToolTip(_translate("MainWindow", "打开工程"))
        self.actionbuild.setText(_translate("MainWindow", "build"))
        self.actionclean.setText(_translate("MainWindow", "clean"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actionsave_project.setText(_translate("MainWindow", "保存工程"))
        self.actionsave_project.setToolTip(_translate("MainWindow", "保存工程"))
import gui_rc
